version: "1"
rules:
  - base: bluefin-main
    upstream: ublue-os:main
    mergeMethod: merge
    mergeUnstable: false

  - base: main
    upstream: bluefin-main
    mergeMethod: rebase
    mergeUnstable: false

label: ":arrow_heading_down: pull"
conflictLabel: "merge-conflict"
