version: "1"
rules:
  - base: main
    upstream: ublue-os:main
    mergeMethod: merge
    mergeUnstable: false

conflictLabel: "merge-conflict"
label: "chore(merge-upstream): :arrow_heading_down: pull"
